name: glockenspiel
favicon: null
layout_spectrum: 1
typography_spectrum: 0.42248
title: glockenspiel
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1b1c17'
    - '#f2cb85'
    - '#78623b'
    - '#4b93a1'
    - '#8bc7d2'
  brandStrength: 0.75
  lightness: 0.375
  saturation: 0.5625
  rhythmicContrast: 0.25
purpose: []
