name: glockenspiel
favicon: null
layout_spectrum: 0.21643371367827058
typography_spectrum: 0.8746311389841139
title: glockenspiel
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1b1c17'
    - '#f2cb85'
    - '#78623b'
    - '#4b93a1'
    - '#8bc7d2'
  brandStrength: 0.75
  lightness: 0.13199280062690377
  saturation: 0.9800312372390181
  rhythmicContrast: 0.23667852417565882
purpose: []
